apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-infra-sandbox-s3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-infrastructure-poc
  source:
    path: infra/s3
    repoURL: https://github.com/sahmed-ssc-spc/dev4-sandbox-workloads.git
    targetRevision: HEAD
  destination:
    namespace: poc-infra-sandbox
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
#      selfHeal: true
      prune: true